apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allowed-operators-configmap.yaml
  - allow-operator-subscriptions-policy.yaml
  - allow-operator-subscriptions-binding.yaml
